version: '3'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recomendation_db
    ports:
      - 5432:5432
    networks:
      - my_network
  
  webapi:
    build:
      context: ./api_recomendation
      dockerfile: Dockerfile
    ports:
      - 80
    depends_on:
      - db
    networks:
      - my_network

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=recomendation_db;Username=root;Password=root

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      - webapi
    networks:
      - my_network

    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fullchain.pem:/etc/letsencrypt/live/recomendacion.api.andersonsinaluisa.com/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/live/recomendacion.api.andersonsinaluisa.com/privkey.pem

networks:
  my_network:
    driver: bridge
