version: '3'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recomendation_db
    volumes:
      - db_data:/var/lib/postgresql/data
  
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=recomendation_db;Username=root;Password=root
  
      



volumes:
  db_data:
